services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIProfile\Menu\LeftSidebarBuilder:
        public: true
        tags:
            - { name: knp_menu.menu_builder, method: build, alias: edgar_ezuiprofile.menu.profile.sidebar_left }
