edgar.ezuiprofile.menu:
    path: /
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Profile:menu'

edgar.ezuiprofile.account:
    path: /account
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Profile:account'

edgar.ezuiprofile.security:
    path: /security
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Profile:security'

edgar.ezuiprofile.content:
    path: /content
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Profile:content'

edgar.ezuiprofile.password:
    path: /account/password
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Account:password'
