edgar.ezuiprofile.menu:
    path: /user/profile
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Profile:menu'

edgar.ezuiprofile.password:
    path: /user/profile/password
    defaults:
        _controller: 'EdgarEzUIProfileBundle:Profile:password'
