imports:
    - { resource: controllers.yml }
    - { resource: menu.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUIProfileBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.user_menu, method: onMenuConfigure }
